#!/usr/bin/env sh
set -eu

# some inspiration from https://raymii.org/s/tutorials/Sign_and_verify_text_files_to_public_keys_via_the_OpenSSL_Command_Line.html

MESSAGE=$1
ID_FILE=$(ssh -G git@github.com | grep identityfile | cut -d' ' -f2 | xargs -I % sh -c 'test -r % && echo % || true' | head -n1)
FINGERPRINT=$(ssh-keygen -E md5 -lf "$ID_FILE" | cut -f2 -d' ')
echo >&2 '>>> signing with this identity file:'"$ID_FILE"' '"$FINGERPRINT"

set -o pipefail
SIGNATURE=$(printf $MESSAGE | openssl dgst -sha256 -sign $ID_FILE | base64 | tr -d '\n')

ESCAPED_MESSAGE=$(printf $MESSAGE | sed 's/"/\\"/g')
echo '{"message":"'$ESCAPED_MESSAGE'","signature":"'$SIGNATURE'"}'
