---
version: 2
jobs:
  build:
    docker:
      - image: circleci/slim-base:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: apk add --no-cache --update openssl
      - run: ./claim
